/**
 * TagsPage — browse ML-generated tags (objects, animals, geography, places)
 * across the entire library. Shows tag frequency bars and lets you filter by
 * category. Provides a quick way to verify Phase 4 tagging results without
 * opening individual files.
 */

import { useEffect, useState, useCallback } from 'react'
import { api, type TopTag } from '../api/client'

type Category = 'all' | 'object' | 'animal' | 'geography' | 'place'

const CATEGORIES: { id: Category; label: string; icon: string; color: string }[] = [
  { id: 'all',       label: 'All',       icon: '🏷️',  color: 'bg-gray-600' },
  { id: 'object',    label: 'Objects',   icon: '📦',  color: 'bg-blue-600' },
  { id: 'animal',    label: 'Animals',   icon: '🐾',  color: 'bg-green-600' },
  { id: 'geography', label: 'Geography', icon: '🌍',  color: 'bg-yellow-600' },
  { id: 'place',     label: 'Places',    icon: '📍',  color: 'bg-pink-600' },
]

const CAT_COLOUR: Record<string, string> = {
  object:    'bg-blue-700 text-blue-100',
  animal:    'bg-green-700 text-green-100',
  geography: 'bg-yellow-700 text-yellow-100',
  place:     'bg-pink-700 text-pink-100',
}

export default function TagsPage() {
  const [category, setCategory] = useState<Category>('all')
  const [tags, setTags]         = useState<TopTag[]>([])
  const [loading, setLoading]   = useState(false)
  const [error, setError]       = useState<string | null>(null)
  const [limit, setLimit]       = useState(50)

  const load = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const data = await api.tags.top(category === 'all' ? undefined : category, limit)
      setTags(data)
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Failed to load tags')
    } finally {
      setLoading(false)
    }
  }, [category, limit])

  useEffect(() => { load() }, [load])

  const maxCount = tags.length > 0 ? Math.max(...tags.map(t => t.count)) : 1

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-white">ML Tags</h1>
        <p className="text-sm text-gray-400 mt-1">
          Auto-generated by Phase 4 — YOLOv11, Places365, OpenCLIP landmarks,
          BioCLIP species, and Nominatim GPS resolution.
        </p>
      </div>

      {/* Category filter */}
      <div className="flex flex-wrap gap-2">
        {CATEGORIES.map(c => (
          <button
            key={c.id}
            onClick={() => setCategory(c.id)}
            className={`px-4 py-1.5 rounded-full text-sm font-medium transition-colors
              ${category === c.id
                ? `${c.color} text-white`
                : 'bg-gray-800 text-gray-400 hover:text-white hover:bg-gray-700'}`}
          >
            {c.icon} {c.label}
          </button>
        ))}

        {/* Limit selector */}
        <div className="ml-auto flex items-center gap-2 text-sm text-gray-400">
          <span>Show top</span>
          {[25, 50, 100].map(n => (
            <button
              key={n}
              onClick={() => setLimit(n)}
              className={`px-2 py-0.5 rounded text-xs transition-colors
                ${limit === n ? 'bg-indigo-600 text-white' : 'bg-gray-800 hover:bg-gray-700 text-gray-300'}`}
            >
              {n}
            </button>
          ))}
        </div>
      </div>

      {/* Error */}
      {error && (
        <div className="bg-red-900/40 border border-red-700 rounded p-3 text-red-300 text-sm">
          {error}
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="text-center py-12 text-gray-500 text-sm">Loading tags…</div>
      )}

      {/* Empty state */}
      {!loading && !error && tags.length === 0 && (
        <div className="text-center py-16 text-gray-500 space-y-2">
          <div className="text-4xl">🏷️</div>
          <p className="text-sm">
            No tags found. Run the pipeline to generate ML tags (Phase 4).
          </p>
        </div>
      )}

      {/* Tag list */}
      {!loading && tags.length > 0 && (
        <div className="space-y-1.5">
          {tags.map((tag, i) => {
            const cat = tag.category ?? category
            const barWidth = Math.max(2, Math.round((tag.count / maxCount) * 100))
            const chipStyle = CAT_COLOUR[cat] ?? 'bg-gray-700 text-gray-200'

            return (
              <div
                key={`${cat}-${tag.label}-${i}`}
                className="flex items-center gap-3 group"
              >
                {/* Category badge (shown in "all" view) */}
                {category === 'all' && tag.category && (
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium w-20 text-center shrink-0 ${chipStyle}`}>
                    {tag.category}
                  </span>
                )}

                {/* Tag label */}
                <span className="text-gray-200 text-sm w-48 shrink-0 truncate" title={tag.label}>
                  {tag.label}
                </span>

                {/* Bar */}
                <div className="flex-1 h-2.5 bg-gray-800 rounded-full overflow-hidden">
                  <div
                    className={`h-full rounded-full transition-all duration-300 ${
                      CAT_COLOUR[cat]?.split(' ')[0] ?? 'bg-indigo-600'
                    }`}
                    style={{ width: `${barWidth}%` }}
                  />
                </div>

                {/* Count */}
                <span className="text-gray-400 text-xs w-10 text-right shrink-0">
                  {tag.count}
                </span>
              </div>
            )
          })}
        </div>
      )}

      {/* Footer note */}
      {!loading && tags.length > 0 && (
        <p className="text-xs text-gray-600 text-center">
          Counts = number of photos tagged with each label.
          Tags are written to files as <code className="text-gray-500">obj:</code>,{' '}
          <code className="text-gray-500">animal:</code>,{' '}
          <code className="text-gray-500">geo:</code>,{' '}
          <code className="text-gray-500">place:</code> prefixed XMP keywords.
        </p>
      )}
    </div>
  )
}
